-- MySQL Script generated by MySQL Workbench
-- Sun Mar 22 20:10:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema primarie
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `primarie` ;

-- -----------------------------------------------------
-- Schema primarie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `primarie` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `primarie` ;

-- -----------------------------------------------------
-- Table `primarie`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primarie`.`administrator` (
  `id` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `primarie`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primarie`.`user` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `primarie`.`adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primarie`.`adress` (
  `id` VARCHAR(255) NOT NULL,
  `number` VARCHAR(255) NULL DEFAULT NULL,
  `street` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK83l3f0l0bktxv2eokobr3hl3f` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK83l3f0l0bktxv2eokobr3hl3f`
    FOREIGN KEY (`user_id`)
    REFERENCES `primarie`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `primarie`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primarie`.`document` (
  `id` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `primarie`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `primarie`.`request` (
  `id` VARCHAR(255) NOT NULL,
  `requestDate` DATETIME NULL DEFAULT NULL,
  `documentType` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` VARCHAR(255) NULL DEFAULT NULL,
  `isAproved` BIT(1) NOT NULL,
  `adress_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKeth3mu17d448fhm1ssmmde5mm` (`documentType` ASC) VISIBLE,
  INDEX `FKqws2fdeknk90txm7qnm9bxd07` (`user_id` ASC) VISIBLE,
  INDEX `FK1ky3kulsift45p8omqa73398a` (`adress_id` ASC) VISIBLE,
  CONSTRAINT `FK1ky3kulsift45p8omqa73398a`
    FOREIGN KEY (`adress_id`)
    REFERENCES `primarie`.`adress` (`id`),
  CONSTRAINT `FKeth3mu17d448fhm1ssmmde5mm`
    FOREIGN KEY (`documentType`)
    REFERENCES `primarie`.`document` (`id`),
  CONSTRAINT `FKqws2fdeknk90txm7qnm9bxd07`
    FOREIGN KEY (`user_id`)
    REFERENCES `primarie`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
